In [1]:
import numpy as np
import pandas as pd

Code for answer 2

In [2]:
df=pd.read_excel("Real estate valuation data set.xlsx")
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.916667,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500000,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1

In [3]:
df = df.iloc[:,1:]

In [4]:
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.916667,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500000,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.666667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250000,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500000,6.5,90.45606,9,24.97433,121.54310,63.9

Code for answer 3

In [5]:
house_train=df.sample(frac=0.8,random_state=100)
house_test=df.drop(house_train.index)

In [6]:
house_train

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
121,2013.500000,13.6,492.23130,5,24.96515,121.53737,48.0
353,2013.500000,4.1,2147.37600,3,24.96299,121.51284,31.3
96,2013.416667,6.4,90.45606,9,24.97433,121.54310,59.5
43,2012.750000,34.4,512.78710,6,24.98748,121.54301,34.1
125,2013.166667,1.1,193.58450,6,24.96571,121.54089,48.6
...,...,...,...,...,...,...,...
402,2012.833333,12.7,187.48230,1,24.97388,121.52981,28.5
94,2012.916667,40.9,167.59890,5,24.96630,121.54026,41.0
214,2013.583333,18.1,1783.18000,3,24.96731,121.51486,20.9
38,2012.666667,3.1,577.96150,6,24.97201,121.54722,47.7
327,2013.416667,3.5,757.33770,3,24.97538,121.54971,36.7

In [7]:
house_test

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
2,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
4,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1
8,2013.500000,31.7,5512.03800,1,24.95095,121.48458,18.8
13,2012.666667,20.4,2469.64500,4,24.96108,121.51046,23.8
...,...,...,...,...,...,...,...
394,2013.500000,32.6,4136.27100,1,24.95544,121.49630,24.7
404,2013.333333,16.4,289.32480,5,24.98203,121.54348,41.2
405,2012.666667,23.0,130.99450,6,24.95663,121.53765,37.2
411,2013.250000,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000000,8.1,104.81010,5,24.96674,121.54067,52.5

In [8]:
xtrain=house_train.iloc[:,:-1]
ytrain=house_train.iloc[:,-1]

In [9]:
xtest=house_test.iloc[:,:-1]
ytest=house_test.iloc[:,-1]

In [10]:
xtrain

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
121,2013.500000,13.6,492.23130,5,24.96515,121.53737
353,2013.500000,4.1,2147.37600,3,24.96299,121.51284
96,2013.416667,6.4,90.45606,9,24.97433,121.54310
43,2012.750000,34.4,512.78710,6,24.98748,121.54301
125,2013.166667,1.1,193.58450,6,24.96571,121.54089
...,...,...,...,...,...,...
402,2012.833333,12.7,187.48230,1,24.97388,121.52981
94,2012.916667,40.9,167.59890,5,24.96630,121.54026
214,2013.583333,18.1,1783.18000,3,24.96731,121.51486
38,2012.666667,3.1,577.96150,6,24.97201,121.54722
327,2013.416667,3.5,757.33770,3,24.97538,121.54971

In [11]:
ytest

0      37.9
2      47.3
4      43.1
8      18.8
13     23.8
       ...
394    24.7
404    41.2
405    37.2
411    40.6
412    52.5
Name: Y house price of unit area, Length: 83, dtype: float64

Code for answer 4

In [12]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression().fit(xtrain,ytrain)

Code for answer 5

In [13]:
l=['X1', 'X2', 'X3', 'X4', 'X5', 'X6']

In [14]:
print("Intercept of trained model:",reg.intercept_)

Intercept of trained model: -16856.651740021036

In [15]:
print('Coefficients of trained model\n')
print('Feature \t Corresponding Weight')
for i in range(6):
  print(l[i],'\t\t',reg.coef_[i])

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.204875352625174
X2 		 -0.2533823236292753
X3 		 -0.004064766015461518
X4 		 1.2461738514031009
X5 		 235.2797869697996
X6 		 21.05222442383043

Code for answer 6

In [16]:
ypred=reg.predict(xtest)

In [17]:
ypred

array([48.10305157, 48.60567387, 46.31770726,  8.64843483, 27.04094547,
       45.34125641, 36.7643925 , 12.51031787, 29.95807907,  9.62697276,
       41.39999304, 12.90299132, 47.20431574, 46.8321532 , 43.25232136,
       54.09840772, 45.21039511, 28.2296393 , 31.32398668, 37.8630469 ,
       23.20477837, 44.39788296, 48.81814563, 48.30552512, 35.26374115,
       30.83170336, 45.0926667 , 38.89512348, 43.07600988, 14.54209277,
       45.5825601 , 54.09840772, 12.60741918,  9.21567292, 51.82508823,
       15.13289431, 30.42686263, 38.90410473, 48.22986592, 33.71192945,
       34.13497871, 42.79999904, 37.01281105, 46.90333263, 13.15714779,
       34.09281736, 36.77389417, 32.60611988, 45.64699742, 23.28400641,
       29.2409343 , 41.15201291, 41.00700388, 42.95674977, 47.614488  ,
       32.58391636, 30.58992926, 45.20048847, 48.42546817, 32.25388543,
       44.97148416, 45.90719919, 37.56942282, 44.14342249, 40.15201179,
       37.13169234, 33.67926074, 50.47198302, 43.37007287,  9.89058446,
       41.07492513, 31.71591093, 29.17351858, 50.11811832, 42.49829146,
       30.16421406, 51.93802078, 40.01551559, 15.3157    , 46.59064601,
       37.90598114, 46.97631521, 44.38551871])

Code for answer 7

In [18]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print('Mean Squared Error:',mean_squared_error(ytest,ypred))
print('R Squared Error:',r2_score(ytest,ypred))

Mean Squared Error: 128.89115621780965
R Squared Error: 0.49508527198874164

Code for answer 8

In [19]:
for i in [0.6,0.7,0.9]:
  print("\nTrain-Test Split:", round(i*100), ':', round((1-i)*100))
  house_train=df.sample(frac=i,random_state=100)
  house_test=df.drop(house_train.index)
  xtrain=house_train.iloc[:,:-1]
  ytrain=house_train.iloc[:,-1]
  xtest=house_test.iloc[:,:-1]
  ytest=house_test.iloc[:,-1]
  reg=LinearRegression().fit(xtrain,ytrain)
  print("\nIntercept:",reg.intercept_)
  print('\nCoefficients of trained model\n')
  print('Feature \t Corresponding Weight')
  for i in range(6):
    print(l[i],'\t\t',reg.coef_[i])
  ypred=reg.predict(xtest)
  print('\nMean Squared Error:',mean_squared_error(ytest,ypred))
  print('R Squared Error:',r2_score(ytest,ypred))
  print('...........................................................................................................................')

Train-Test Split: 60 : 40

Intercept: -17991.10904411932

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.004327887503438
X2 		 -0.22126119238787284
X3 		 -0.004093239103497681
X4 		 1.07494808252008
X5 		 263.96971735512705
X6 		 27.813215142718843

Mean Squared Error: 102.02506185585156
R Squared Error: 0.5411586204301471
...........................................................................................................................

Train-Test Split: 70 : 30

Intercept: -17998.62707448733

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.48341922280664
X2 		 -0.23022118176680273
X3 		 -0.00405746603178625
X4 		 1.1501244729789895
X5 		 249.4636215206719
X6 		 22.919940456504396

Mean Squared Error: 108.35187785221213
R Squared Error: 0.5390719100421066
...........................................................................................................................

Train-Test Split: 90 : 10

Intercept: -19397.644666012795

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.780078837487483
X2 		 -0.2642137886914589
X3 		 -0.003926948822338461
X4 		 1.3216193868892716
X5 		 211.72920113368522
X6 		 37.2679524635208

Mean Squared Error: 183.43795234385226
R Squared Error: 0.3786005775144077
...........................................................................................................................

Code for answer 9

In [20]:
traintestsplit=[0.8, 0.6, 0.7, 0.9]
lambdas_list=[0.001,0.005,0.01,0.05,0.1,0.5]

In [21]:
from sklearn import linear_model
for i in traintestsplit:
  for j in lambdas_list:
    print('\nTrain-Test Split:', round(i*100), ':', round((1-i)*100))
    print("Lambda =",j)
    house_train=df.sample(frac=i,random_state=100)
    house_test=df.drop(house_train.index)
    xtrain=house_train.iloc[:,:-1]
    ytrain=house_train.iloc[:,-1]
    xtest=house_test.iloc[:,:-1]
    ytest=house_test.iloc[:,-1]
    reg = linear_model.Lasso(alpha=j)
    reg.fit(xtrain,ytrain)
    print("\nIntercept:",reg.intercept_)
    print('\nCoefficients of trained model\n')
    print('Feature \t Corresponding Weight')
    for k in range(6):
      print(l[k],'\t\t',reg.coef_[k])
    ypred=reg.predict(xtest)
    print('\nMean Squared Error:',mean_squared_error(ytest,ypred))
    print('R Squared Error:',r2_score(ytest,ypred))
    print('.........................................................................................................')

Train-Test Split: 80 : 20
Lambda = 0.001

Intercept: -14979.22163253864

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.203860793698499
X2 		 -0.2526232302414939
X3 		 -0.004261827557958535
X4 		 1.2467840923687272
X5 		 223.34034679991555
X6 		 8.075745822069084

Mean Squared Error: 128.53329488313375
R Squared Error: 0.49648714829869023
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.005

Intercept: -12932.545782927886

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.213757795080309
X2 		 -0.2495137721037688
X3 		 -0.0045805888434202816
X4 		 1.2648175772482857
X5 		 179.88937841678046
X6 		 0.0

Mean Squared Error: 128.5034026978076
R Squared Error: 0.49660424713670603
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.01

Intercept: -11632.41498240116

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.229344649569644
X2 		 -0.24561010229022268
X3 		 -0.004870915746680132
X4 		 1.2909504964381207
X5 		 126.5674881377486
X6 		 0.0

Mean Squared Error: 129.29958913512266
R Squared Error: 0.4934852879292655
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.05

Intercept: -7821.2596636561675

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 3.9061661497093136
X2 		 -0.23604798423443454
X3 		 -0.005561499011352691
X4 		 1.348392503606532
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 134.14002672127157
R Squared Error: 0.4745234886950668
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.1

Intercept: -6532.282839539764

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 3.2658975112100155
X2 		 -0.23552328486762458
X3 		 -0.005563881907555657
X4 		 1.3402857018069843
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 134.8227922042125
R Squared Error: 0.4718488416655062
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.5

Intercept: 42.69629250771309

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 0.0
X2 		 -0.23138382314030345
X3 		 -0.0056177212353131075
X4 		 1.2706337563899084
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 139.37691125148552
R Squared Error: 0.4540086589286938
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.001

Intercept: -16154.233254950404

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.009096981133153
X2 		 -0.22020048291709726
X3 		 -0.00428392090140566
X4 		 1.073590807031867
X5 		 252.62542289481277
X6 		 14.952363207321204

Mean Squared Error: 101.70341685096412
R Squared Error: 0.5426051673382275
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.005

Intercept: -13357.41350978009

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.043220199309468
X2 		 -0.21605917045889989
X3 		 -0.004651698603581819
X4 		 1.0898040830008278
X5 		 210.65118832340866
X6 		 0.0

Mean Squared Error: 101.19256340057561
R Squared Error: 0.5449026489341267
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.01

Intercept: -12192.217796751445

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.0935832634093705
X2 		 -0.21093453682678898
X3 		 -0.0049091359877865256
X4 		 1.1211554218256925
X5 		 159.92623408295125
X6 		 0.0

Mean Squared Error: 101.24664372182372
R Squared Error: 0.5446594313485874
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.05

Intercept: -7897.41135251986

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 3.943818921882862
X2 		 -0.19473775511880528
X3 		 -0.005720589439676991
X4 		 1.2173908880936588
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 104.84923974549037
R Squared Error: 0.5284573325753705
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.1

Intercept: -6615.634350882915

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 3.307123685223595
X2 		 -0.19465422591301218
X3 		 -0.005719959298973425
X4 		 1.2120646094482403
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 105.26471242134068
R Squared Error: 0.5265888107407053
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.5

Intercept: 42.324300649240854

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 0.0
X2 		 -0.19318909009314494
X3 		 -0.005761237832926151
X4 		 1.1557414602481222
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 108.56478070387203
R Squared Error: 0.5117472820428761
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.001

Intercept: -16126.546576256198

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.485646435777018
X2 		 -0.22956024459199842
X3 		 -0.004254102191932767
X4 		 1.1491286133707297
X5 		 237.91147426789445
X6 		 9.854306102307584

Mean Squared Error: 108.01125521058393
R Squared Error: 0.5405209162496063
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.005

Intercept: -13920.572925106788

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.499215341159634
X2 		 -0.2270740763595515
X3 		 -0.004579258116994611
X4 		 1.1656522779232832
X5 		 196.44249975354396
X6 		 0.0

Mean Squared Error: 107.61945262886081
R Squared Error: 0.5421876415451339
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.01

Intercept: -12697.414936936151

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.517531325112847
X2 		 -0.22401214219109217
X3 		 -0.004851693082212269
X4 		 1.1922631482180266
X5 		 145.9828325687709
X6 		 0.0

Mean Squared Error: 107.76765007981363
R Squared Error: 0.5415572106808209
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.05

Intercept: -8492.774704178191

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.239717062901932
X2 		 -0.21492134171211852
X3 		 -0.005643525832152124
X4 		 1.2648606224906855
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 111.12173368494646
R Squared Error: 0.527288963740222
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.1

Intercept: -7188.699719473296

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 3.5919523114385146
X2 		 -0.21446616528098658
X3 		 -0.005650663451608147
X4 		 1.256273969677397
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 111.55388280742274
R Squared Error: 0.5254506045576368
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.5

Intercept: 42.71212041941313

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 0.0
X2 		 -0.21082197861024932
X3 		 -0.005727188024523582
X4 		 1.1842845064393277
X5 		 0.0
X6 		 -0.0

Mean Squared Error: 115.35167261355348
R Squared Error: 0.5092948347075839
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.001

Intercept: -17437.604992777076

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.795209350993515
X2 		 -0.26371317228808655
X3 		 -0.0041315685238631885
X4 		 1.3242285500724338
X5 		 199.54590186900845
X6 		 23.394444404417563

Mean Squared Error: 182.7800589913359
R Squared Error: 0.38082920329270065
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.005

Intercept: -13554.776381088352

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.841803501602732
X2 		 -0.2611942174545034
X3 		 -0.00460489057298017
X4 		 1.341104647648802
X5 		 154.16850611550402
X6 		 0.0

Mean Squared Error: 183.02752134225582
R Squared Error: 0.37999092004769186
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.01

Intercept: -12306.410345612825

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.8873604121208265
X2 		 -0.25757499206352025
X3 		 -0.004882109283131657
X4 		 1.3680662080703752
X5 		 100.50376361749434
X6 		 0.0

Mean Squared Error: 186.23559873469927
R Squared Error: 0.36912349913788656
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.05

Intercept: -9204.726238750343

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.5933118303744305
X2 		 -0.2504393809272348
X3 		 -0.00540325258582788
X4 		 1.4145910153565187
X5 		 0.0
X6 		 0.0

Mean Squared Error: 194.60412244771987
R Squared Error: 0.34077497182451866
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.1

Intercept: -7958.102465377333

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 3.974079044524943
X2 		 -0.24985677154353048
X3 		 -0.005406313691136549
X4 		 1.4081506522484855
X5 		 0.0
X6 		 0.0

Mean Squared Error: 195.08079845639057
R Squared Error: 0.3391602231167623
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.5

Intercept: 42.483560455913995

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 0.0
X2 		 -0.2453692584059295
X3 		 -0.0054471940734013595
X4 		 1.3520720981985257
X5 		 0.0
X6 		 0.0

Mean Squared Error: 199.18775721786852
R Squared Error: 0.3252478251099925
.........................................................................................................

In [22]:
from sklearn import linear_model
for i in traintestsplit:
  for j in lambdas_list:
    print('\nTrain-Test Split:', round(i*100), ':', round((1-i)*100))
    print("Lambda =",j)
    house_train=df.sample(frac=i,random_state=100)
    house_test=df.drop(house_train.index)
    xtrain=house_train.iloc[:,:-1]
    ytrain=house_train.iloc[:,-1]
    xtest=house_test.iloc[:,:-1]
    ytest=house_test.iloc[:,-1]
    reg = linear_model.Ridge(alpha=j)
    reg.fit(xtrain,ytrain)
    print("\nIntercept:",reg.intercept_)
    print('\nCoefficients of trained model\n')
    print('Feature \t Corresponding Weight')
    for k in range(6):
      print(l[k],'\t\t',reg.coef_[k])
    ypred=reg.predict(xtest)
    print('\nMean Squared Error:',mean_squared_error(ytest,ypred))
    print('R Squared Error:',r2_score(ytest,ypred))
    print('.........................................................................................................')

Train-Test Split: 80 : 20
Lambda = 0.001

Intercept: -16508.33695920927

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.215213750771623
X2 		 -0.25285374352773404
X3 		 -0.00412079092161384
X4 		 1.2493566554997941
X5 		 227.780032729588
X6 		 19.556087621199666

Mean Squared Error: 128.82957784170355
R Squared Error: 0.4953264974531981
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.005

Intercept: -15366.845662118081

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.250772268061429
X2 		 -0.2510371173547527
X3 		 -0.004308504145607054
X4 		 1.2604484524876858
X5 		 202.0591108970242
X6 		 14.859979788377135

Mean Squared Error: 128.72232671369585
R Squared Error: 0.49574664012020475
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.01

Intercept: -14337.155002238775

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.285356560355796
X2 		 -0.2492697137072091
X3 		 -0.004484090932814426
X4 		 1.271462573836131
X5 		 177.1142216982771
X6 		 10.940393379506054

Mean Squared Error: 128.77234821420285
R Squared Error: 0.4955506872475304
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.05

Intercept: -11291.828129457212

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.405419520228474
X2 		 -0.24300477084454375
X3 		 -0.0050533885322044106
X4 		 1.31217724103478
X5 		 89.29187156860155
X6 		 1.9396510894404853

Mean Squared Error: 130.16501293534935
R Squared Error: 0.4900951001496825
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.1

Intercept: -10333.046457298751

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.4469377299642705
X2 		 -0.2405531170845359
X3 		 -0.005254846136860439
X4 		 1.3287663709799569
X5 		 55.171686771301765
X6 		 0.37362636805262545

Mean Squared Error: 131.2257087554622
R Squared Error: 0.4859399590427945
.........................................................................................................

Train-Test Split: 80 : 20
Lambda = 0.5

Intercept: -9217.453193361824

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.439946633546598
X2 		 -0.23754778441453983
X3 		 -0.00548546346072784
X4 		 1.3494139354152321
X5 		 13.611857893875559
X6 		 -0.15065602481197285

Mean Squared Error: 132.96586641059676
R Squared Error: 0.479123112527319
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.001

Intercept: -17487.959636443502

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.026523463783906
X2 		 -0.22020655718050153
X3 		 -0.00417118400743117
X4 		 1.0801009065877083
X5 		 253.35991947498985
X6 		 25.48566289103842

Mean Squared Error: 101.85411268289282
R Squared Error: 0.5419274369633587
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.005

Intercept: -15922.658199812082

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.100128414862337
X2 		 -0.2167194161425638
X3 		 -0.004420414956919499
X4 		 1.0976249761080932
X5 		 218.33023904275106
X6 		 18.584685500220598

Mean Squared Error: 101.45066551999007
R Squared Error: 0.5437418759790524
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.01

Intercept: -14613.447169461419

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.167909115414672
X2 		 -0.21351689842640095
X3 		 -0.004638204543444624
X4 		 1.1143548429301076
X5 		 186.22660831321562
X6 		 13.285978699550775

Mean Squared Error: 101.29747135380912
R Squared Error: 0.5444308422121907
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.05

Intercept: -11232.305230047414

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.377991952809665
X2 		 -0.20345746000082546
X3 		 -0.005258359911734171
X4 		 1.1705941900397745
X5 		 85.7546371804261
X6 		 2.629106980255467

Mean Squared Error: 102.1582832264266
R Squared Error: 0.540559478647227
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.1

Intercept: -10290.897243871821

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.442831924929931
X2 		 -0.19999404864040188
X3 		 -0.005451198265113355
X4 		 1.1911909409187997
X5 		 51.253851219573384
X6 		 0.8975344239103142

Mean Squared Error: 102.9276962770266
R Squared Error: 0.5370991666496204
.........................................................................................................

Train-Test Split: 60 : 40
Lambda = 0.5

Intercept: -9201.284167176553

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.4384931696691075
X2 		 -0.19609598111466467
X3 		 -0.005656828730241909
X4 		 1.2155003894642047
X5 		 12.161390134257347
X6 		 0.03567048921935757

Mean Squared Error: 104.13021904568667
R Squared Error: 0.5316910130440317
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.001

Intercept: -17574.689660243577

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.496836264047866
X2 		 -0.22971187432190293
X3 		 -0.004123801075650107
X4 		 1.1537579287354467
X5 		 240.84770295195364
X6 		 20.979959016130735

Mean Squared Error: 108.22282602989286
R Squared Error: 0.5396208955432933
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.005

Intercept: -16220.232372873435

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.542322055626982
X2 		 -0.22798559902689797
X3 		 -0.00434155956991619
X4 		 1.1664204497041903
X5 		 211.67783731890944
X6 		 15.075876152467027

Mean Squared Error: 107.89933980763045
R Squared Error: 0.5409970035490859
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.01

Intercept: -15044.434308419082

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.585613051014982
X2 		 -0.22634034251670956
X3 		 -0.004539201351774503
X4 		 1.1789735587007248
X5 		 183.92375120356783
X6 		 10.387155705780154

Mean Squared Error: 107.75351654671097
R Squared Error: 0.5416173346264922
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.05

Intercept: -11827.84152621686

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.72890436796501
X2 		 -0.22075522662160962
X3 		 -0.005142905675041141
X4 		 1.2248717218952656
X5 		 90.02788209695012
X6 		 0.8403807517276581

Mean Squared Error: 108.42814211310868
R Squared Error: 0.5387474824382302
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.1

Intercept: -10897.222303074985

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.775407206006951
X2 		 -0.21866545245606056
X3 		 -0.005344052792915532
X4 		 1.2432376458905423
X5 		 55.01767551593225
X6 		 -0.39367892954060785

Mean Squared Error: 109.1446500224046
R Squared Error: 0.5356994630719027
.........................................................................................................

Train-Test Split: 70 : 30
Lambda = 0.5

Intercept: -9829.98625582776

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.758853628575417
X2 		 -0.2161727409813706
X3 		 -0.005567179602956178
X4 		 1.265756504483499
X5 		 13.397495389551615
X6 		 -0.3493748691147706

Mean Squared Error: 110.36061785232286
R Squared Error: 0.5305267448836778
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.001

Intercept: -19037.10735187041

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.792627072610505
X2 		 -0.2638510455405948
X3 		 -0.003978134627840341
X4 		 1.3242859793224195
X5 		 205.5987453283602
X6 		 35.35333721872581

Mean Squared Error: 183.51744444884886
R Squared Error: 0.3783312965531568
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.005

Intercept: -17834.926375845716

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.836041713394018
X2 		 -0.26258100165719656
X3 		 -0.0041517050982182455
X4 		 1.3336578392002527
X5 		 184.29803210730907
X6 		 29.119678712001665

Mean Squared Error: 183.90357757160564
R Squared Error: 0.377023263529359
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.01

Intercept: -16721.03761704881

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 4.878681461217587
X2 		 -0.2613097003148469
X3 		 -0.004317042861714839
X4 		 1.3430918349225995
X5 		 163.2196974113949
X6 		 23.579578563558645

Mean Squared Error: 184.45256728479785
R Squared Error: 0.37516355082340425
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.05

Intercept: -13226.57848609184

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 5.031101185838585
X2 		 -0.2565004425771676
X3 		 -0.004874467835577418
X4 		 1.3792044577334603
X5 		 85.45901085646496
X6 		 8.280663059486812

Mean Squared Error: 187.8934888255745
R Squared Error: 0.36350736609752565
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.1

Intercept: -12049.888790070041

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 5.087208483535788
X2 		 -0.2544795967874182
X3 		 -0.005080212634460392
X4 		 1.3945499885357269
X5 		 53.62392436344765
X6 		 4.2107620904016745

Mean Squared Error: 189.93937634587584
R Squared Error: 0.3565768846603874
.........................................................................................................

Train-Test Split: 90 : 10
Lambda = 0.5

Intercept: -10654.716090301368

Coefficients of trained model

Feature 	 Corresponding Weight
X1 		 5.100365005685965
X2 		 -0.2518791316902776
X3 		 -0.005321824896289268
X4 		 1.4143492539054416
X5 		 13.491120743564926
X6 		 0.7594468900249177

Mean Squared Error: 193.08322030729576
R Squared Error: 0.34592705567434867
.........................................................................................................