In [14]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt 
from sklearn.preprocessing import StandardScaler

In [15]:
from sklearn.datasets import fetch_california_housing

california_housing = fetch_california_housing(as_frame=True)

In [16]:
X = california_housing.frame

In [17]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [19]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [20]:
 K = np.array(list(range(2,6)))

In [24]:
for i in K:
  kmeans = KMeans(n_clusters=i, random_state=100, n_init='auto', tol=1e-3, max_iter=10**4).fit(X)
  a=kmeans.labels_
  b=kmeans.cluster_centers_
  print("\n\nK:",i)
  print("Clusters (labels):", a)
  print("Centroid:",b)

K: 2
Clusters (labels): [1 1 1 ... 0 0 0]
Centroid: [[-0.41561153  0.02256455 -0.19694637 -0.04012094  0.02176253  0.01196085
   0.03874073  0.02046731 -0.44856675]
 [ 1.15635512 -0.06278131  0.54796348  0.11162842 -0.06054984 -0.03327865
  -0.10778825 -0.05694616  1.24804635]]


K: 3
Clusters (labels): [0 0 0 ... 0 0 0]
Centroid: [[-4.69075950e-02  2.27237114e-02  2.82156223e-02 -3.14004474e-02
  -1.21856948e-01 -1.65354262e-02  1.07241327e+00 -1.05865957e+00
  -9.97677691e-02]
 [ 3.65387051e-02 -1.20266866e-02 -8.86860866e-02 -5.14346145e-02
   9.69902093e-02  1.26473503e-02 -8.04147756e-01  7.87369604e-01
   7.66953715e-02]
 [-2.63702243e-01 -7.88792874e-01  1.09341678e+01  1.20829575e+01
  -1.01936753e+00 -5.53313648e-02  9.87451109e-01  6.95256638e-02
  -3.96296543e-01]]


K: 4
Clusters (labels): [1 1 1 ... 0 0 0]
Centroid: [[-2.69710473e-01  2.58695693e-02 -3.76930049e-02 -2.00566760e-02
  -1.24062411e-01 -1.50978323e-02  1.11193360e+00 -1.05587560e+00
  -3.25308501e-01]
 [ 1.57264450e+00 -3.20876612e-02  5.04354304e-01 -8.28769218e-02
  -1.24669466e-01  1.88974921e-02 -2.97466756e-01  1.02168922e-01
   1.64956506e+00]
 [-2.62041297e-01 -7.89981594e-01  1.07306890e+01  1.18317659e+01
  -9.97236930e-01 -5.53168665e-02  9.49116013e-01  9.80367516e-02
  -3.83682665e-01]
 [-3.15037344e-01 -3.42367381e-03 -2.24689341e-01 -4.92440444e-02
   1.48005044e-01  6.00173750e-03 -7.86514048e-01  7.99811863e-01
  -2.96053511e-01]]


K: 5
Clusters (labels): [1 1 1 ... 0 0 0]
Centroid: [[-2.69898685e-01  2.57652169e-02 -3.76892507e-02 -2.00751754e-02
  -1.24405880e-01 -1.50933768e-02  1.11184150e+00 -1.05588443e+00
  -3.25780857e-01]
 [ 1.57192697e+00 -3.01361751e-02  5.03894893e-01 -8.27654055e-02
  -1.31336670e-01 -3.26556027e-02 -2.97284659e-01  1.01822361e-01
   1.65225198e+00]
 [-2.62041297e-01 -7.89981594e-01  1.07306890e+01  1.18317659e+01
  -9.97236930e-01 -5.53168665e-02  9.49116013e-01  9.80367516e-02
  -3.83682665e-01]
 [-3.14239870e-01 -4.14194126e-03 -2.24145265e-01 -4.92254790e-02
   1.49844563e-01  1.10072885e-02 -7.86315371e-01  7.99662087e-01
  -2.95751292e-01]
 [ 3.34551548e+00  1.29997497e+00 -9.14401602e-01 -5.55691418e-01
   5.32880467e+00  1.19419103e+02  1.25855037e+00 -1.20305254e+00
  -6.01041006e-01]]

In [27]:
def kmeans(data, k, tol=1e-3, max_iter=10**4):
    centroids = data[np.random.choice(data.shape[0], size=k, replace=False)]
    manhattan = lambda x, y: np.sum(np.abs(x - y))
    for i in range(max_iter):
        dist = np.zeros((data.shape[0], k))
        for j in range(k):
            dist[:, j] = np.apply_along_axis(lambda x: manhattan(x, centroids[j]), 1, data)
        labels = np.argmin(dist, axis=1)
        new_centroids = np.zeros((k, data.shape[1]))
        for j in range(k):
            mask = labels == j
            if np.sum(mask) > 0:
                new_centroids[j, :] = np.mean(data[mask, :], axis=0)
            else:
                new_centroids[j, :] = centroids[j, :]
        if np.sum(np.abs(new_centroids - centroids)) < tol:
            break
        centroids = new_centroids
    return labels, centroids

In [28]:
for i in K:
  c,d = kmeans(X, i, tol=1e-3, max_iter=10**4)
  print("\n\nK:",i)
  print("Clusters (labels):", c)
  print("Centroid:",d)

K: 2
Clusters (labels): [0 0 0 ... 1 1 1]
Centroid: [[ 1.25819584 -0.10140602  0.44988424 -0.06568928 -0.00811636 -0.01520712
  -0.11829589 -0.06014291  1.22662347]
 [-0.41896524  0.03376708 -0.14980645  0.0218738   0.00270266  0.0050638
   0.03939122  0.02002692 -0.40845199]]


K: 3
Clusters (labels): [1 1 1 ... 2 2 2]
Centroid: [[-0.2605232   0.0062962  -0.19294605 -0.0320739   0.11609768  0.00211555
  -0.79095543  0.79812907 -0.19232729]
 [ 1.93911086 -0.11897341  0.68142247 -0.07728934 -0.10426911 -0.00265947
  -0.30495533  0.11251929  1.7423655 ]
 [-0.22286697  0.0260851   0.05157782  0.06327478 -0.11879966 -0.00194678
   1.10080989 -1.0547616  -0.2537558 ]]


K: 4
Clusters (labels): [0 0 0 ... 1 1 1]
Centroid: [[ 2.44072348e+00  9.00087188e-02  8.50628163e-01 -3.62165833e-02
  -1.92964419e-01  1.64425896e-02  3.45625906e-01 -6.25583469e-01
   2.05111033e+00]
 [-2.22661217e-01  2.23560204e-02  4.75822829e-02  6.34798208e-02
  -1.19860426e-01 -1.74309234e-03  1.12838801e+00 -1.08456271e+00
  -2.56895540e-01]
 [-5.17872046e-01  8.10171407e-02 -3.04449599e-01 -2.15661239e-02
   1.08922593e-01  1.08628190e-02 -7.36926440e-01  7.70031739e-01
  -4.20558196e-01]
 [ 8.28210165e-01 -2.57307556e-01  3.03584798e-01 -7.29356255e-02
   7.04659849e-02 -2.59970142e-02 -8.28643060e-01  7.54134886e-01
   8.09412190e-01]]


K: 5
Clusters (labels): [1 1 1 ... 2 2 2]
Centroid: [[-0.09489102 -1.06323901  0.04278923  0.09904915  0.75515951 -0.00580997
  -0.811591    0.91901325 -0.32106267]
 [ 0.80750687  0.21412265  0.20594851 -0.10242567 -0.05681732  0.02609962
   0.93842469 -1.27064257  0.97650911]
 [-0.54021779 -0.09261527  0.04172978  0.13798357 -0.17155914 -0.01106506
   1.14978729 -0.93133976 -0.71617889]
 [-0.42391548  0.53370128 -0.34224096 -0.08749713 -0.14554748  0.00885142
  -0.78432048  0.74702798 -0.22543385]
 [ 1.50146963 -0.11996014  0.50647681 -0.08429963 -0.11780404 -0.02587193
  -0.81751281  0.70427446  1.44935308]]